version: '3.1'

services:
  db:
    image: postgres:latest
    container_name: db_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: desafio
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data